#!/bin/sh

# Set default values
TIMER=0
SELECT=0
QUALITY=5
COPY_SS=0
SAVE_SS=0
NAME_SS="$(date '+%Y%m%d-%H%M%S').png"
SAVE_SS_DIR="$HOME/Pictures/Screenshots"

while getopts :scxt:q:n:p: flag; do
    case "${flag}" in
        t) TIMER=${OPTARG};;
        s) SELECT=1;;
        c) COPY_SS=1;;
        x) SAVE_SS=1;;
        q) QUALITY=${OPTARG};;
        n) NAME_SS=${OPTARG};;
        p) SAVE_SS_DIR=${OPTARG};;
        *) echo "usage: $0 [-xsc] [-t time(s)] [-q quality(1-10)] [-n name.png] [-p path/to/picture]"; exit 2 ;;
    esac
done

# If -x or -c options are not given, set both for default behavior
if [ $SAVE_SS -eq 0 ] && [ $COPY_SS -eq 0 ]; then
    SAVE_SS=1
    COPY_SS=1
fi

# Ensure directory exists
[ $SAVE_SS -eq 1 ] && mkdir -p "${SAVE_SS_DIR}"

# Wait for the timer, if specified
sleep "$TIMER"

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    # Wayland screenshot using grim and slurp
    if [ $SELECT -eq 1 ]; then
        GEOM=$(slurp)
        [ -z "$GEOM" ] && exit 1
        grim -g "$GEOM" "${SAVE_SS_DIR}/${NAME_SS}" || exit 2
    else
        grim "${SAVE_SS_DIR}/${NAME_SS}" || exit 2
    fi

    # Copy to clipboard if requested
    if [ $COPY_SS -eq 1 ]; then
        wl-copy < "${SAVE_SS_DIR}/${NAME_SS}"
    fi
else
    # X11 screenshot using maim
    [ $SELECT -eq 1 ] && TAGS="-s"
    maim $TAGS -m "$QUALITY" "${SAVE_SS_DIR}/${NAME_SS}" || exit 2

    # Copy to clipboard if requested
    if [ $COPY_SS -eq 1 ]; then
        xclip -selection clipboard -target image/png -i "${SAVE_SS_DIR}/${NAME_SS}"
    fi
fi

# Cleanup and Notification
SHOW=""
if [ $SAVE_SS -eq 1 ] && [ $COPY_SS -eq 1 ]; then
    SHOW="$(echo "${SAVE_SS_DIR}" | sed -e "s|${HOME}|~|g")/${NAME_SS} (+CLIPBOARD)"
elif [ $SAVE_SS -eq 0 ] && [ $COPY_SS -eq 1 ]; then
    SHOW="CLIPBOARD"
    # Note: in this modernized script, we always save to a temp file first for Wayland/X11 consistency
    # then copy and remove if SAVE_SS is 0.
    rm "${SAVE_SS_DIR}/${NAME_SS}"
elif [ $SAVE_SS -eq 1 ] && [ $COPY_SS -eq 0 ]; then
    SHOW="$(echo "${SAVE_SS_DIR}" | sed -e "s|${HOME}|~|g")/${NAME_SS}"
fi

# Send notification
if [ $? -eq 0 ]; then
    notify-send --urgency=normal --hint=string:desktop-entry:"📷" "Screenshot taken" "Screenshot saved at $SHOW"
else
    notify-send --urgency=normal --hint=string:desktop-entry:"🚫" "Screenshot error" "Failed to capture screenshot"
fi
